/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  role: string;
  createdAt: string;
}

export interface AuditLog {
  id: string;
  auditType: string;
  status: string;
  createdAt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
