/**
 * API Hooks - Generated by MOSS.AO
 */
import { useState, useEffect, useCallback } from 'react';
import { apiClient } from '../lib/api';

interface UseApiOptions<T> {
  initialData?: T;
  onSuccess?: (data: T) => void;
  onError?: (error: Error) => void;
}

export function useApi<T>(
  fetchFn: () => Promise<{ data?: T; error?: string }>,
  options: UseApiOptions<T> = {}
) {
  const [data, setData] = useState<T | undefined>(options.initialData);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const execute = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetchFn();
      if (response.error) {
        throw new Error(response.error);
      }
      if (response.data) {
        setData(response.data);
        options.onSuccess?.(response.data);
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      setError(error);
      options.onError?.(error);
    } finally {
      setLoading(false);
    }
  }, [fetchFn]);

  useEffect(() => {
    execute();
  }, [execute]);

  return { data, loading, error, refetch: execute };
}

export function useMutation<T, P>(
  mutationFn: (params: P) => Promise<{ data?: T; error?: string }>,
  options: UseApiOptions<T> = {}
) {
  const [data, setData] = useState<T | undefined>();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback(async (params: P) => {
    setLoading(true);
    setError(null);

    try {
      const response = await mutationFn(params);
      if (response.error) {
        throw new Error(response.error);
      }
      if (response.data) {
        setData(response.data);
        options.onSuccess?.(response.data);
      }
      return response;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      setError(error);
      options.onError?.(error);
      throw error;
    } finally {
      setLoading(false);
    }
  }, [mutationFn]);

  return { mutate, data, loading, error };
}
