/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  username: string;
  email: string;
  createdAt: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  portfolioId: string;
  assetName: string;
  quantity: number;
  priceAtTransaction: number;
  transactionType: string;
  createdAt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
