/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  username: string;
  email: string;
  createdAt: string;
}

export interface InsurancePolicy {
  id: string;
  userId: string;
  coverageAmount: number;
  premiumPaid: number;
  isActive: boolean;
}

export interface Trade {
  id: string;
  userId: string;
  tradeType: any;
  quantity: number;
  pricePerToken: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
