// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title Contract
 * @dev Base contract generated by MOSS.AO
 */
contract Contract {
    string public name;
    address public owner;

    event NameChanged(string newName);

    constructor(string memory _name) {
        name = _name;
        owner = msg.sender;
    }

    function setName(string memory _name) public {
        require(msg.sender == owner, "Only owner can set name");
        name = _name;
        emit NameChanged(_name);
    }
}
